"use client";

import { useRef } from "react";
import { formatCurrency, getPricingUnit } from "@/lib/pricing";
import { formatPhone } from "@/lib/format";
import { Drawer } from "./drawer";

interface SnapshotMed {
  medication: string;
  form: string;
  price: number;
}

interface ComparisonMed {
  medication: string;
  form: string;
  previousPrice: number | null;
  newPrice: number | null;
}

interface PharmacyContact {
  contactName: string | null;
  phone: string | null;
  email: string | null;
  fax: string | null;
}

export interface SnapshotData {
  id: string;
  actionType: string;
  notes: string | null;
  performedBy: string | null;
  performedAt: string;
  changedFields: string | null;
}

interface Props {
  open: boolean;
  onClose: () => void;
  log: SnapshotData | null;
  pharmacyName: string;
  pharmacyContact: PharmacyContact;
}

const ACTION_LABELS: Record<string, string> = {
  created: "Contract Created",
  updated: "Contract Updated",
  renewed: "Contract Renewed",
  verified: "Contract Verified",
  deleted: "Medication Removed",
};

function parsePricingData(changedFields: string | null): {
  snapshot: SnapshotMed[];
  comparison: ComparisonMed[];
  effectiveDate: string | null;
} {
  if (!changedFields) return { snapshot: [], comparison: [], effectiveDate: null };
  try {
    const parsed = JSON.parse(changedFields);
    const snapshot: SnapshotMed[] = parsed.snapshot ?? [];
    let comparison: ComparisonMed[] = parsed.comparison ?? [];
    const effectiveDate: string | null = parsed.effectiveDate ?? null;

    // For individual update entries that store {medication, oldPrice, newPrice}
    if (parsed.medication && comparison.length === 0 && snapshot.length === 0) {
      comparison = [{
        medication: parsed.medication,
        form: "",
        previousPrice: parsed.oldPrice ?? null,
        newPrice: parsed.newPrice ?? null,
      }];
    }
    return { snapshot, comparison, effectiveDate };
  } catch {
    return { snapshot: [], comparison: [], effectiveDate: null };
  }
}

export function ContractSnapshotDrawer({ open, onClose, log, pharmacyName, pharmacyContact }: Props) {
  const printRef = useRef<HTMLDivElement>(null);
  if (!log) return null;

  const eventLabel = ACTION_LABELS[log.actionType] ?? `Contract ${log.actionType}`;
  const { snapshot, comparison, effectiveDate } = parsePricingData(log.changedFields);
  const hasComparison = comparison.length > 0;
  const hasSnapshot = snapshot.length > 0;
  const hasPricing = hasSnapshot || hasComparison;

  const fmtPhone = (v: string | null) => v ? formatPhone(v) : null;

  function handleDownloadPdf() {
    if (!printRef.current) return;
    const content = printRef.current.innerHTML;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`<!DOCTYPE html><html><head><title>${pharmacyName} \u2014 ${eventLabel}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:48px;color:#111;font-size:13px;line-height:1.6}
h1{font-size:22px;font-weight:600;margin-bottom:2px}
h2{font-size:13px;font-weight:600;margin:20px 0 8px;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em}
.subtitle{font-size:13px;color:#6b7280;margin-bottom:24px}
.meta-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px 24px;margin-bottom:16px}
.meta-grid dt{font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#9ca3af}
.meta-grid dd{font-size:13px;color:#374151;margin-bottom:8px}
table{width:100%;border-collapse:collapse;margin:8px 0 16px}
th{text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#9ca3af;padding:8px;border-bottom:2px solid #e5e7eb}
th[align=right]{text-align:right}
td{padding:10px 8px;border-bottom:1px solid #f3f4f6;font-size:13px}
td[align=right]{text-align:right}
.mono{font-weight:500;font-variant-numeric:tabular-nums}
.green{color:#16a34a}.red{color:#dc2626}.muted{color:#9ca3af}
.tag{display:inline-block;font-size:10px;font-weight:500;padding:1px 6px;border-radius:4px;margin-left:6px}
.tag-new{background:#eef2ff;color:#4f46e5}.tag-removed{background:#fef2f2;color:#dc2626}
.unit{font-size:10px;color:#9ca3af;margin-left:4px}
.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:10px;color:#9ca3af}
@media print{body{padding:24px}}
</style></head><body>${content}
<div class="footer">Generated by Bisk &middot; ${new Date().toLocaleDateString()}</div>
</body></html>`);
    win.document.close();
    setTimeout(() => win.print(), 300);
  }

  return (
    <Drawer open={open} onClose={onClose} title={eventLabel}>
      <div className="space-y-5">
        {/* Printable content — everything inside ref renders to PDF */}
        <div ref={printRef}>
          {/* 1. Header */}
          <h1>{pharmacyName}</h1>
          <div className="subtitle">{eventLabel} &mdash; {new Date(log.performedAt).toLocaleDateString()}</div>

          {/* 2. Metadata */}
          <h2>Details</h2>
          <dl className="meta-grid">
            <dt>Event Date</dt>
            <dd>{new Date(log.performedAt).toLocaleDateString()}</dd>
            {effectiveDate && <><dt>Effective Date</dt><dd>{new Date(effectiveDate).toLocaleDateString()}</dd></>}
            {log.performedBy && <><dt>Performed By</dt><dd>{log.performedBy}</dd></>}
            {log.notes && <><dt>Notes</dt><dd>{log.notes}</dd></>}
          </dl>

          {/* 3. Pharmacy Contact */}
          <h2>Pharmacy Contact</h2>
          <dl className="meta-grid">
            {pharmacyContact.contactName && <><dt>Contact</dt><dd>{pharmacyContact.contactName}</dd></>}
            {pharmacyContact.phone && <><dt>Phone</dt><dd>{fmtPhone(pharmacyContact.phone)}</dd></>}
            {pharmacyContact.email && <><dt>Email</dt><dd>{pharmacyContact.email}</dd></>}
            {pharmacyContact.fax && <><dt>Fax</dt><dd>{fmtPhone(pharmacyContact.fax)}</dd></>}
          </dl>

          {/* 4. Pricing Data — THE MAIN SECTION */}
          {hasComparison ? (
            <>
              <h2>Pricing Changes</h2>
              <table>
                <thead>
                  <tr>
                    <th>Medication</th>
                    <th align="right">Previous</th>
                    <th align="right">New</th>
                    <th align="right">Difference</th>
                  </tr>
                </thead>
                <tbody>
                  {comparison.map((c, i) => {
                    const diff = (c.previousPrice != null && c.newPrice != null) ? Math.round((c.newPrice - c.previousPrice) * 100) / 100 : null;
                    const unit = c.form ? getPricingUnit(c.form) : "";
                    return (
                      <tr key={i}>
                        <td>
                          {c.medication}
                          {unit && <span className="unit">/ {unit}</span>}
                          {c.previousPrice === null && <span className="tag tag-new">New</span>}
                          {c.newPrice === null && <span className="tag tag-removed">Removed</span>}
                        </td>
                        <td align="right" className="mono">{c.previousPrice != null ? formatCurrency(c.previousPrice) : "\u2014"}</td>
                        <td align="right" className="mono">{c.newPrice != null ? formatCurrency(c.newPrice) : "\u2014"}</td>
                        <td align="right" className={`mono ${diff != null && diff > 0 ? "red" : diff != null && diff < 0 ? "green" : "muted"}`}>
                          {diff != null ? `${diff > 0 ? "+" : ""}${formatCurrency(diff)}` : "\u2014"}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </>
          ) : hasSnapshot ? (
            <>
              <h2>Contract Pricing</h2>
              <table>
                <thead>
                  <tr>
                    <th>Medication</th>
                    <th>Unit</th>
                    <th align="right">Contract Price</th>
                  </tr>
                </thead>
                <tbody>
                  {snapshot.map((s, i) => (
                    <tr key={i}>
                      <td>{s.medication}</td>
                      <td className="muted">{getPricingUnit(s.form)}</td>
                      <td align="right" className="mono">{formatCurrency(s.price)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </>
          ) : (
            <p className="muted" style={{ marginTop: 12 }}>No pricing data available for this event.</p>
          )}
        </div>

        {/* 5. Download PDF button */}
        {hasPricing && (
          <div className="pt-3 border-t border-gray-100">
            <button onClick={handleDownloadPdf}
              className="w-full flex items-center justify-center gap-2 bg-indigo-600 text-white rounded-md px-4 py-2 text-sm font-medium hover:bg-indigo-700 transition-colors">
              <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Download PDF
            </button>
          </div>
        )}
      </div>
    </Drawer>
  );
}
